# Generated by Django 2.0.1 on 2020-07-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverpage',
            field=models.ImageField(blank=True, null=True, upload_to='media/cover'),
        ),
    ]
