# Generated by Django 4.1.4 on 2023-01-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_book_coverpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverpage',
            field=models.ImageField(blank=True, null=True, upload_to='cover'),
        ),
    ]
